user:
  api/v1/ratings/findByRecipeId/{idRecipe}:
    "read:any": ["*"]
  api/v1/ratings/{idRating}:
    "update:any": ["*"]
    "delete:any": ["*"]
  api/v1/ratings:
    "read:any": ["*"]
    "create:any": ["*"]
admin:
  api/v1/ratings:
    "read:any": ["*"]
    "create:any": ["*"]
  api/v1/ratings/findByRecipeId/{idRecipe}:
    "read:any": ["*"]
  api/v1/ratings/{idRating}:
    "update:any": ["*"]
    "delete:any": ["*"]