name: Node.js CI

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ main, develop ]
    paths-ignore:
      - '**/*.md'

jobs:  
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Run docker compose
        run: docker-compose -f "./.github/workflows/docker-compose.yaml" up -d --build
      - name: Run tests
        run: npm test
        env:
          CI: true

  oktetoRelease:
      name: Deploy to Okteto
      needs: test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Okteto Login
          uses: okteto/login@latest
          with:
            token: ${{ secrets.RATING_TOKEN }}
        - name: Okteto Deploy
          uses: okteto/pipeline@latest
          with:
            name: ratings-service
            namespace: youryummy-maribelrb22
            variables: >-
              NODE_ENV=production,
              NAMESPACE=youryummy-maribelrb22,
              MONGO_PROTO=mongodb+srv,
              MONGO_HOST=ratings-service.olmvwaw.mongodb.net,
              MONGO_USER=rservice,
              MONGO_PWD=wqgCgZtZJ7qu0O6m,
              MONGO_DBNAME=ratings,
